python3 ./1_RegisterCandidate.py
python3 ./2_ApproveCandidate.py
python3 ./3_RejectCandidate.py
python3 ./4_BlackNode.py
python3 ./5_WhiteNode.py
python3 ./6_QuitNode.py
python3 ./7_VoteForPeer.py
python3 ./8_UnVoteForPeer.py
python3 ./9_Withdraw.py
python3 ./10_updateConfig.py
python3 ./11_UpdateGlobalParam.py
python3 ./12_UpdateSplitCurve.py
python3 ./13_TransferPenalty.py
